services:
  postgres:
    image: postgres:16
    container_name: gastos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gastos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      gastos_net:
        ipv4_address: 172.28.0.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  gastos_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

volumes:
  postgres_data: